spring.application.name=hospital-management
spring.datasource.url=jdbc:postgresql://localhost:5432/hospitaldb
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.sql.show-sql=true
spring.sql.properties.hibernate.dialect=org.hibern√ate.dialect.PostgreSQLDialect
server.port=9090